<a href="https://colab.research.google.com/github/kartikeygupta547/cognitive-computing/blob/main/Copy_of_Untitled6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:

a) Addition of 2 in all the element

b) Multiply 3 with all the elements

c) Divide every element by 2

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr2 = arr + 2
print("Original array:", arr)
print("Array after adding 2:", arr2)
arr3 = arr * 3
print("Array after multiplying by 2:", arr3)
arr4 = arr / 2
print("Array after dividing by 2:", arr4)

Original array: [1 2 3 4 5]
Array after adding 2: [3 4 5 6 7]
Array after multiplying by 2: [ 3  6  9 12 15]
Array after dividing by 2: [0.5 1.  1.5 2.  2.5]


Q2 a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
reversed_arr = arr[::-1]
print("Original array:", arr)
print("Reversed array:", reversed_arr)


Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]


b) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])


ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
import numpy as np

# Array x
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)
most_frequent_value = values[np.argmax(counts)]
indices = np.where(x == most_frequent_value)[0]
print("Array x:")
print("Most frequent value:", most_frequent_value)
print("Indices:", indices)

# Array y
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(y, return_counts=True)
most_frequent_value = values[np.argmax(counts)]
indices = np.where(y == most_frequent_value)[0]
print("\nArray y:")
print("Most frequent value:", most_frequent_value)
print("Indices:", indices)

Array x:
Most frequent value: 1
Indices: [0 5 7 8 9]

Array y:
Most frequent value: 1
Indices: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:

a) Access 1st row, 2nd column

b) Access 3rd row, 1st column

In [ ]:
import numpy as np
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)
element = arr[0, 1]
print(" 1st row, 2nd column:",element)
element2 = arr[2, 0]
print("3rd row, 1st column",element2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
 1st row, 2nd column: 20
3rd row, 1st column 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [ ]:
import numpy as np
kartikey = np.linspace(10, 100, 25)
print("Dimensions:", kartikey.ndim)
print("Shape:", kartikey.shape)
print("Total elements:", kartikey.size)
print("Data type:", kartikey.dtype)
print("Total bytes consumed:", kartikey.nbytes)
transposed_reshape = kartikey.reshape(kartikey.shape[0], 1)
print("\nTransposed using reshape():\n", transposed_reshape)
transposed_T = kartikey.T
print("\nTransposed using T attribute:\n", transposed_T)
print("\nIs reshape() equivalent to T for a 1-D array?", np.array_equal(transposed_reshape.flatten(), transposed_T))

Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes consumed: 200

Transposed using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transposed using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Is reshape() equivalent to T for a 1-D array? True


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [ ]:
import numpy as np
ucs420_kartikey = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Mean:", np.mean(ucs420_kartikey))
print("Median:", np.median(ucs420_kartikey))
print("Max:", np.max(ucs420_kartikey))
print("Min:", np.min(ucs420_kartikey))
print("Unique elements:", np.unique(ucs420_kartikey))
reshaped_ucs420_kartikey = ucs420_kartikey.reshape(4, 3)
print("\nReshaped array:\n", reshaped_ucs420_kartikey)
resized_ucs420_kartikey = np.resize(ucs420_kartikey, (2, 3))
print("\nResized array:\n", resized_ucs420_kartikey)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array:
 [[10 20 30]
 [40 50 60]]
